### ISSUE TITLE
Jouer sur la taille d'affichage des médias

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#100]
Sur la timeline les médias sont tous de taille proche. C'est peut-être une volonté initiale ? 
Sinon, intégrer le paramétrage de différentes tailles pour éviter la superposition systématique en cas d'afflux important. 
Ces tailles pourraient dépendre également d'une importance accordée à certains médias à posteriori. 
Elle pourrait se déterminer après l'envoi, en fonction de votes (type likes par ouverture ?) ou en fonction d'un temps de vie (type snap) ? 
(C'est peut-être l'objet d'une autre issue).

**Comment by louis-ev** [comment]
C’est une idée qui a été un peu exploré avant la v1 oui. Le soucis récurrent étant que quand on utilise le système de zoom/dézoom, un média qui est grand peu masquer tous les autres s’il l’est trop.
Et si la taille des médias s’adapte à la taille du zoom, même soucis avec des médias petits qui deviendraient microscopiques.
Comment gérer ça ?

**Comment by louis-ev** [comment]
Il y a peut-être une échelle de temps ou la bascule se fait vers une vue plus classique type bibliothèque (évoquée déjà ici #88 ).

Par exemple dans le logiciel Photos d’Apple, les photos sont sectionnées par journée de capture : 

![image](https://user-images.githubusercontent.com/1948417/40412135-c18fd564-5e72-11e8-8f46-a89c126771a6.png)

**Comment by ThibM** [comment]
Hmm oui pas simple cette affaire. 
La vue bibliothèque est une option pratique sur téléphone en effet. Par lieux, dates, personnes, objets etc. (cf. IA google photos)
Maintenant, par défaut, il y a une impression de surcharge assez rapide passé un certain nombre de médias chargé.
L'idée serait d'éviter une action supplémentaire de l'utilisateur ou peut-être avant l'envoi par différents paramètres/tags/étiquettes qui attribueraient une échelle d'ordonnancement des tailles.
Ou après coup, comme si un média pouvait gagnait en importance selon qu'il est survolé/consulté/commenté ?

**Comment by ThibM** [comment]
Dans le cas de médias très proches les uns des autres, et donc de chevauchement difficiles à distinguer au survol de la souris, ne pourrait-il pas y avoir une compensation sur l'axe Y par exemple ? 
A savoir pour un écart de temps minimum entre 2 médias, incrémenter une contrainte en Y qui les espacerait (un minimum) dans un ordre de chargement. 
_Positionnement aléatoire en Y déjà évoqué je crois. Doit pouvoir à nouveau rejoindre un autre sujet... désolé pour les renvois ! _

**Comment by louis-ev** [comment]
En fait plus ça va et plus je me dis que la position en Y devrait être gérée automatiquement pour éviter les superpositions au maximum. J’ai l’impression que la fonctionnalité de placement manuel sur l’axe des Y est peu utilisée et peu utile… je me trompe ? Dans ton cas personnel ça donne quoi ?

**Comment by ThibM** [comment]
Oui, je pense que ce serait une fonctionnalité intéressante, ne serait-ce que pour distinguer les medias dès le premier affichage.
Dans mon cas, je m'en sers lorsque je veux rendre visible plusieurs images sur la timeline, pour garder le flux chronologique, sans passer par la vue "liste".
Après, il pourrait être envisageable d'utiliser un placement manuel en Y comme mode d'édition qui affecterait une sémantique (une taille ?) aux différents média.
Ex. plus on les descend, moins ils ont d'importance (flou, doublons, dossier etc.).
Ou encore : placer sur la première ligne ceux à mettre en tête de rubriques d'une éventuelle publication à exporter.
