### ISSUE TITLE
Réduire la plage d'affichage des durées sans média

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#101]
En écho à un usage sur plusieurs mois – issue de @Pia pour éviter les longs scroll désertique.

**Comment by louis-ev** [comment]
Je comprend bien cette issue mais elle est particulièrement délicate à traiter : le temps serait "dilaté" et "compressé" par endroits, ce qui casse l’idée d’une organisation temporelle relative.
Dans certains softs de calendrier il est possible de "replier" la période entre 20h et 8h du matin sur tous les jours, le systématisme de cette règle permettant de rester dans une structure très "carrée" qui me parait importante.

Est-ce qu’on peut dire que s’il n’y a pas de médias actuellement visibles, il y aurait deux boutons pour sauter aux premiers médias dans le futur et dans le passé (par rapport au temp où on est ?) ?

**Comment by ThibM** [comment]
Ah oui c'est une bonne idée. Comme sur la timeline after effects où tu peux bondir d'une image-clé à l'autre sans avoir à tout faire défiler. 

Je comprends la structuration temporelle. A voir s'il n'y aurait pas une sorte de passe-passe à trouver comme pour les échelles logarithmiques...

**Comment by louis-ev** [comment]
Ça demande de revoir toute la logique de placement des médias — qui se base actuellement sur un calcul linéaire. En terme de performance ça me parait être optimal (il faut sinon mettre en place une logique beaucoup plus complexe de temps *dilaté* et *contracté*, que suivent tous les éléments).
Pour commencer les petites flèches iront bien :)

**Comment by ThibM** [comment]
Oui ! 
Et entre le silence d'or et l'horreur du vide, on verra bien s'il est vraiment nécessaire d'adjoindre matière à ce désert :) 
Peut-être une place pour la glose !
