### ISSUE TITLE
Répartition sur l'axe y

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#102]
Selon l'ordre d'arrivée, le poids des fichiers, l'importance (autre issue) et/ou le type de fichier, afficher les médias aussi suivant un axe vertical

**Comment by louis-ev** [comment]
En gros, l’organisation sur l’axe Y pourrait suivre soit une logique de placement utilisateur, soit certaines données propres à chaque média, c’est ça ? Type, couleur, etc. ?

**Comment by ThibM** [comment]
Oui voilà. Notamment pour éviter le chevauchement par défaut.

**Comment by louis-ev** [comment]
Est-ce que cela ne serait pas controlé dans la barre de média, à gauche ?
Par exemple en sélectionnant un groupement par type de média, dans la timeline les médias s’organisent comme ça. En ajoutant un filtre, les médias de la timeline se masquent et s’affichent comme dans la liste.
Est-ce que ça pourrait marcher ?
