### ISSUE TITLE
Affichage des médias en 

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#103]
Une fois cliqué sur un média, permettre le défilement vers les autres à proximité. 
Soit par un affichage de miniatures dans la fenêtre d’aperçu (cf. scroll dans la galerie iPhone) ou de simples flèches de carousel.

**Comment by louis-ev** [comment]
Celui qui vient tout de suite après dans la chronologie / celui qui vient tout de suite avant ?
C’est une bonne idée oui

**Comment by ThibM** [comment]
Idéalement dans un sens et dans l'autre, oui.
J'ai en tête le système tactile très pratique sur téléphone pour faire défiler les photos comme en mixant les images façon stop-motion, mais des flèches ce serait déjà très bien aussi !

**Comment by louis-ev** [comment]
Il y a aussi une question de performance ici, si tu consultes sur smartphone il faut que l’image arrive par le wifi d’abord (ce qui peut prendre une seconde ou plus, suivant la qualité du routeur).
Du coup des flèches me paraissent plus adapté pour un défilement controlé par étape.

**Comment by louis-ev** [comment]
Ok ! Prochaine version du coup.
Je dois l’implémenter dans do•doc, c’est quasiment la même logique et ça sera aussi utile là-bas.
