### ISSUE TITLE
Curseur d'affichage type table de montage vidéo

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#104]
Accéder plus rapidement au plage de temps que par ouverture du menu latéral et scroll des jours ou de la liste de médias.
Ex. timeline de montage vidéo avec slider de proportionnalité du temps.

**Comment by louis-ev** [comment]
Je pensais à placer une sorte de minimap au niveau de la barre de scroll, pour qu’elle donne une idée de la densité des médias sur telle ou telle période (et éviter de scroller dans du vide pendant longtemps).
En gros une vue schématisée des contenus présents, sur 30-40 pixels de haut. Ça se rejoint non ?

**Comment by ThibM** [comment]
Je pensais à l'équivalent de la _Barre de défilement de zoom_ dans les logiciels de montage (https://helpx.adobe.com/fr/premiere-pro/using/creating-changing-sequences.html) mais la vue schématisée ça peut être bien aussi, oui ! 
Tu la verrais en remplacement de la barre de scroll ? L'affichage ne risque pas d'être compliqué si la timeline est très longue ?

**Comment by louis-ev** [comment]
Si, c’est toujours délicat car une timeline de 4h aura pas les mêmes contraintes d’une timeline de 12 mois (voir plus).

Voici par exemple la vue schématisée sur le logiciel Visual Studio Code :

![image](https://user-images.githubusercontent.com/1948417/40411559-1ba52ace-5e71-11e8-9407-d53ef55a7c1c.png)

La bande large à droite est un aperçu dé-zoomé du code, celle encore plus à droite est une version abstraite qui permet de comprendre où se trouve les *points d’intérêt* en quelque sorte. Intéressant non ?
