### ISSUE TITLE
Paramétrage d’un ordre d’affichage lorsqu’on scroll sur une période donnée.

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#105]
A un moment du scroll, tu rentres dans une période spéciale où se joue un ordre d'apparition des éléments, animés comme en couch mode. Avec des effets du type :
Oskar Fischinger : https://www.youtube.com/watch?v=6Xc4g00FFLk
Michel Gagné : https://www.youtube.com/watch?v=UVWKtXDvr04

**Comment by louis-ev** [comment]
J’avais un peu testé ça mais autant ça marche très bien quand il y a peu d’éléments, ça se casse la gueule complet quand il y a 100 ou 200 médias à révéler. Du coup j’ai laissé ça de côté temporairement, à voir si ça apporte réellement qqchose !

**Comment by ThibM** [comment]
Oui ce serait pour un mode présentation disons. 
Et dans l'idée que l'ordre attribué puisse faire défiler des éléments en stop-motion, quasi-automatiquement à partir d'un grand nombre d'éléments (comme les importations de séquence jpg dans AE)

**Comment by louis-ev** [comment]
Pourrais-tu me faire une vidéo de l’effet dont tu parles dans AE ? Merci !
