### ISSUE TITLE
Echelle de temps inférieure

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#109]
Pour les prises de notes denses, serait-il envisageable d'avoir une échelle d'affichage inférieure à la seconde ?
![capture d ecran 2018-10-30 a 17 33 22](https://user-images.githubusercontent.com/1745279/47734128-0b5ba680-dc6a-11e8-939a-35fb2c4f5998.png)

**Comment by louis-ev** [comment]
Oui absolument ! Soit ça, soit un affichage en mode "grille" comme suggéré ici : https://github.com/l-atelier-des-chercheurs/Les-Cahiers-du-Studio/issues/88
ou là : https://github.com/l-atelier-des-chercheurs/Les-Cahiers-du-Studio/issues/100

Et sinon dans la dernière version (pas encore exportée en app) y a le système de navigation "média suivant" "média précédent", ça peut aider à la consultation aussi non ?

![image](https://user-images.githubusercontent.com/1948417/47863514-bd74a900-ddf7-11e8-8e6b-5e59245cc568.png)

**Comment by ThibM** [comment]
Oui bien pratique les flèches. 
Quid de l'intérêt de les insérer plutôt dans le cadre de l'image pour les rendre bien apparentes et réduire l'espace d'aller-retour entre "suivante" et "précédente" ?

**Comment by louis-ev** [comment]
Hmm en terme de logique c’est vraiment toute la fenêtre qu’on change (l’encart de gauche aussi). Je pense qu’en terme d’interface et d’animation c’est important de garder ça.
Cela dit il me semble avoir mis des raccourcis clavier pour pouvoir rapidement switcher, ça peut remplir ce rôle aussi non ? La question est : a-t’on vraiment besoin de basculer entre suivant et précédent rapidement ? 

À terme j’aimerai aussi intégrer un petit aperçu du média suivant dans la flèche.
