### ISSUE TITLE
BUG – Lecture son timeline 

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#110]
La lecture de bande sonore directement dans la timeline ne fonctionne pas (Version 1.7.6-dev (1.7.6-dev))

**Comment by louis-ev** [comment]
C’est pas un bug malheureusement, c’est un manque de temps pour implémenter ça :(
Voir l’issue #17 , suite de la discussion là-bas :)
