### ISSUE TITLE
Position du pointer des médias

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#115]
Le pointer blanc (qui devient noir au survol) situé en haut à droite des médias n'aide pas à leur repérage dans la timeline. 
Peut-être dû en partie aux superpositions qui recouvrent les points. Y a-t-il eu des essais d'ancrage à partir des bords supérieurs gauches toujours visibles des média ?

**Comment by louis-ev** [comment]
Hmm non, parce que ça paraissait moins gênant que les médias dépassent "vers le passé" plutôt que "vers le futur". À voir si la solution n’est pas juste d’éviter les superpositions de manière automatique…
