### ISSUE TITLE
Rapport de plantage intégral - résolu

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#116]
Cas de bug pour info. 
> Création d'un nouveau dossier depuis l'interface de l'appli CDS
> import avec le BT "+" de la timeline de plus d'images que possible donc message d'erreur
> copié collé de toutes les images depuis le finder directement dans le dossier dont certains s'ajoutent alors en doublons
> Suppression depuis le finder de tous les médias du dossier 
> A l'ouverture dossier dans l'appli, message de chargement tourne en boucle
> Au redémarrage de l'appli, disparition de tous les dossiers (pj !)
> Suppression du dossier depuis le finder et fermeture de l'appli
> Recréation du dossier depuis l'interface et import de toutes les images directement depuis le finder 
> OK
Peut provenir d'un tiret long dans le titre ?

![capture d ecran 2019-01-04 a 14 15 41](https://user-images.githubusercontent.com/1745279/50689863-9fac0600-102b-11e9-9d9e-faf5aea70c39.png)

**Comment by louis-ev** [comment]
Tu as du supprimer le fichier `meta.txt` du dossier en supprimant tous ses médias. Ce qui perd l’appli, du coup elle n’arrive plus à les charger. Elle devrait plutôt zapper la lecture de ce dossier mais ne le fait pas. Je regarde comment améliorer ça.
