### ISSUE TITLE
appimage on mint sarah realtime kernel

### ISSUE THREAD

**Issue by lep0le** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#117]
Bonjour pas de demarrage de l'application.
erreur comme suit:
~ $ '/home/lep0le/Téléchargements/les-cahiers-du-studio-1.6.1-x86_64(1).AppImage' 
installed: X-AppImage-BuildId=b0eb8980-5dda-11a8-1ff3-6b81355a8de9 image: X-AppImage-BuildId=b0eb8980-5dda-11a8-1ff3-6b81355a8de9
[22:30:41] Main module initialized at 20190209_223041
Starting app Les Cahiers du Studio
{ http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.9.211.38',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  electron: '1.8.2',
  chrome: '59.0.3071.115',
  'atom-shell': '1.8.2' }
Not logging to a file
[22:30:41] ——— Starting les-cahiers app version 1.6.1
[22:30:41] Found defaults for windowState: 
[22:30:41] [object Object]
(node:12184) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EROFS: read-only file system, mkdir '/tmp/.mount_les-caKct7AD/app/resources/app/cache'
(node:12184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Une piste ...?

**Comment by louis-ev** [comment]
Ça a l’air lié à des questions de permission en écriture de dossiers.

Au lancement l’app essaye d’accéder au dossier du cache qui lui est attribué et de le vider. Si ça n’est pas possible elle peut crasher, mais c’est la première fois que je vois ça.

Peut-être essayer en `sudo` ?
