### ISSUE TITLE
Incompatibilité Catalina 

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#134]
Message d'ouverture depuis la migration... 
<img width="532" alt="Capture d’écran 2020-09-09 à 17 02 30" src="https://user-images.githubusercontent.com/1745279/92616469-8ce8da80-f2be-11ea-9ed5-dbdcfdb6d8d2.png">

**Comment by louis-ev** [comment]
:(

Tu es bien sur la version 2.3.4 ?
https://github.com/l-atelier-des-chercheurs/Les-Cahiers-du-Studio/releases/tag/v2.3.4

**Comment by ThibM** [comment]
Je l'ai réinstallé pour être sûr, même type de message d'erreur avec juste un cadre gris qui s'affiche et reste en fond en plus... 
<img width="532" alt="Capture d’écran 2020-09-13 à 19 48 53" src="https://user-images.githubusercontent.com/1745279/93024954-639bb780-f5fa-11ea-9f3d-b6f3c5123a2b.png">

**Comment by louis-ev** [comment]
Ça m semble pas être un soucis lié à Catalina à vue de nez mais je n’ai pas ce soucis sur mon mac.
L’appli s’installe ? démarre ? ça le fait à quel moment ?
Peut-tu essayer de renommer le dossier les-cahiers en les-cahiers2 et relancer l’appli ? Il y a peut-être un soucis avec l’une de tes timelines.

**Comment by ThibM** [comment]
Bien vu ! Ca a résolu le problème.
J'ai du à nouveau mal m'y prendre en faisant me sauvegardes. Je clos
l'issue :)


Le mar. 15 sept. 2020 à 11:53, Louis Eveillard <notifications@github.com> a
écrit :
