### ISSUE TITLE
images

### ISSUE THREAD

**Issue by EllaSTV** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#31]
Dans le projet rencontre les images ne sont toujours pas visible, alors qu'elles sont bien dans le documents les cahiers

**Comment by louis-ev** [comment]
Elles le sont ici, il me manque des infos pour identifier le soucis.
Peux-tu créer une nouvelle timeline et en importer qq unes, et me dire si elles s’affichent ?
Dans le dossier _thumbs, est-ce qu’elles sont bien générées ?

**Comment by louis-ev** [comment]
La version 1.0.0-beta.3 est en ligne, pouvez-vous tester à nouveau ?

**Comment by louis-ev** [comment]
Je ferme, apparement ce soucis est résolu.
