### ISSUE TITLE
Longueur d'onde

### ISSUE THREAD

**Issue by EllaSTV** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#34]
J’ai souhaité crée un nouveau dossier pour le projet de Bérangère « Longueur d’onde ». Seulement dans l’accueille l’apostrophe ne passe pas.

**Comment by louis-ev** [comment]
L’apostrophe française passe, mais la minute américaine non ;)

![image](https://user-images.githubusercontent.com/1948417/33025150-7430b02c-ce0d-11e7-90b5-28c416042be9.png)
![image](https://user-images.githubusercontent.com/1948417/33025153-75598ab4-ce0d-11e7-9e13-af459ea4525e.png)

Je vais voir ce que je peux faire.

**Comment by louis-ev** [comment]
Ella, as-tu pu tester avec une apostrophe ’ ?
