### ISSUE TITLE
legende

### ISSUE THREAD

**Issue by EllaSTV** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#35]
Serait-il possible d’associer une légende à une image ?

**Comment by louis-ev** [comment]
Dans l’idée, il fallait créer un bloc texte à proximité pour créer une légende mais c’est de plus en plus clair qu’une légende pour tous les médias serait bien utile. J’ajoute ça.

**Comment by louis-ev** [comment]
À venir dans la quatrième bêta.
