### ISSUE TITLE
mot clé ? 

### ISSUE THREAD

**Issue by EllaSTV** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#36]
Que signifie  « mot clé » un par ligne ?

**Comment by louis-ev** [comment]
L’idée était de pouvoir lister des mots-clés, par exemple : 

Mise en scène
Éclairage
etc.

Ce qui permet de retrouver des médias avec la sidebar, qui ont en commun des mots-clés.
Un par ligne, c’est pour simplifier leur création.

**Comment by louis-ev** [comment]
Un champ légende serait certainement beaucoup plus souple et utile, je vais remplacer à la prochaine version du coup.

**Comment by louis-ev** [comment]
Voir #35
