### ISSUE TITLE
mot de passe

### ISSUE THREAD

**Issue by EllaSTV** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#37]
Nous souhaiterions accéder aux projets via un mot de passe.

**Comment by louis-ev** [comment]
Je ne comprends pas ce mot de passe ? Le mot de passe bloque l’accès à tous les médias, exceptés ceux qui sont publics pour un projet.
De manière à pouvoir permettre un accès, mais uniquement aux contenus déclarés *publics*. Vous voudriez un autre comportement ?
