### ISSUE TITLE
Deux formats de dates différents dans la page d'édition des médias

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#57]
![screen shot 2017-12-03 at 12 33 17](https://user-images.githubusercontent.com/4678296/33524968-31503c8c-d826-11e7-8927-483aba633e41.png)
Dans Date et date de création. 
Je propose de tout mettre en français

**Comment by louis-ev** [comment]
Effectivement, c’est gênant.
Note perso pour ce bug : https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/datetime-local

**Comment by sarahgarcin** [comment]
J'ai remarqué que c'était aussi le cas dans l'édition des dossiers

**Comment by louis-ev** [comment]
J’ai pas ça ici… Tu aurai ton ordi de configuré en anglais ?

**Comment by louis-ev** [comment]
Apparement c'est quand on a un ordi configuré en anglais. Vu qu’on peut maintenant changer la langue de l’app, ça n’a plus autant de sens de corriger ce bug. Le datetime-local n’étant pas implémenté sur Firefox, il n’y a pas de solution évidente… Je ferme du coup.
