### ISSUE TITLE
Quand on agrandit la liste c'est vraiment énorme, surtout pour les images en portrait

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#58]
![screen shot 2017-12-03 at 12 36 11](https://user-images.githubusercontent.com/4678296/33524992-9e82853a-d826-11e7-9d5f-ff51cfd6aade.png)

**Comment by louis-ev** [comment]
![image](https://user-images.githubusercontent.com/1948417/33731463-7a151db0-db83-11e7-862d-ff7f4ed11046.png)
