### ISSUE TITLE
Pourquoi la taille du bloc blanc ne s'adapte pas à la taille du texte ? 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#59]
![screen shot 2017-12-03 at 12 38 41](https://user-images.githubusercontent.com/4678296/33525014-f9c72a22-d826-11e7-8ab4-19cc73474119.png)

**Comment by louis-ev** [comment]
Duplicate of #39
