### ISSUE TITLE
Envoyer une vidéo depuis son téléphone, le format qui apparait dans la timeline est étrange

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#60]
![screen shot 2017-12-03 at 12 48 42](https://user-images.githubusercontent.com/4678296/33525085-7049ffd4-d828-11e7-9c9a-101ada61e1b0.png)

Ma vidéo apparait en format paysage alors qu'elle est en portrait.

**Comment by louis-ev** [comment]
Le ratio est pas le bon du coup ? C'est systématique, pour toutes les vidéos de ton téléphone ?
Peux-tu mettre en PJ dans un message ici ce fichier vidéo que je l’importe ?

**Comment by sarahgarcin** [comment]
Après d'autres tests, le format à l'importation est toujours le même quelque soit l'orientation de la vidéo portrait / paysage. 
Ici dans ces trois vidéos, 2 sont en portraits et une en paysage: 
![screen shot 2017-12-03 at 14 24 09](https://user-images.githubusercontent.com/4678296/33525721-b3a7e82e-d835-11e7-81c5-733e3f79039e.png)

**Comment by louis-ev** [comment]
cf fichier joint

[vid-20171203-124658.mp4.zip](https://github.com/l-atelier-des-chercheurs/Les-Cahiers-du-Studio/files/1524759/vid-20171203-124658.mp4.zip)

**Comment by sarahgarcin** [comment]
Par contre pour les photos ça marche très bien.

**Comment by louis-ev** [comment]
Peux-tu regarder les fichiers .txt correspondant à ces médias, et me dire si ils ont une valeur "ratio" ? J’ai l’impression que FFMPEG a pas bien été installé.
Ensuite, aller voir dans `les-cahiers/_thumbs/nom-de-ton-dossier` si il existe bien des fichiers du nom du fichier vidéo (des screenshots).

**Comment by sarahgarcin** [comment]
Vidéo en portrait: 
ratio: 0.5625

Vidéo en paysage: 
ratio: 0.5625

Oui les fichiers thumbs correspondant aux vidéos existe bien, il sont dans le bon format (portrait pour les vidéos en portrait et paysage pour les vidéos en paysage)

**Comment by louis-ev** [comment]
Hmm donc le ratio est identique que la vidéo soit portrait ou paysage
J’ai l’impression que FFMPEG ne comprend pas l’instruction portrait ou paysage, du coup interprète le fichier comme identique. Je pense que le portrait ou paysage est comme dans les images, une propriété meta mais pas réellement dans les pixels même. À confirmer du coup.

**Comment by sarahgarcin** [comment]
Oui après c'est pas méga grave dans un premier temps.

**Comment by louis-ev** [comment]
Ce qui serait utile, ce serait de voir si ça vient de FFMPEG (plus que probable) qui a du mal avec le format vidéo de ton téléphone.

Dans ce même fichier méta, as-tu un champ `duration` ?
Dans Les Cahiers, ces médias là ont-ils deux petits repères (un pour le début, un pour la fin) ?

**Comment by sarahgarcin** [comment]
oui j'ai un champ duration, qui parait correcte. 
Il n'y a pas deux petits repères, mais je pense que mes vidéos sont trop courtes pour les voir elle font moins de 5sec

**Comment by louis-ev** [comment]
Ok, merci pour les infos.
À voir dans FFMPEG pour une info rotation du coup !

**Comment by louis-ev** [comment]
Penser à appliquer la logique de non-étirement des thumbs à celles de la vidéo
