### ISSUE TITLE
Home - Changer la phrase en en français ?

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#61]
Pour accéder aux Cahiers avec un autre appareil, connectez vous au même réseau wifi puis entrez l’url dans votre navigateur (ignorez le message de sécurité):

**Comment by louis-ev** [comment]
Tu proposes de remplacer celle-ci : 
> Pour accéder aux Cahiers avec un autre appareil, connectez vous au même réseau wifi puis entrez l’url dans le navigateur web (puis ignorez le message de sécurité)
par 
> Pour accéder aux Cahiers avec un autre appareil, connectez vous au même réseau wifi puis entrez l’url dans votre navigateur (ignorez le message de sécurité):
c'est bien ça ? question de lisibilité ?

**Comment by sarahgarcin** [comment]
Ahhh mais je viens de comprendre, c'est une phrase traduite en fr / en et qui détecte la langue de ton ordi. Et mon ordi est en anglais. 
Ok je ferme l'issue. Sorry
