### ISSUE TITLE
Problèmes de port quand php est lancé dans le terminal

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#63]
Lorsque PHP est lancé via le terminal avec le port 8080 (php -S localhost:8080), l'application ne fonctionne plus. Il y a un conflit entre les ports 8080. Normalement, l'app devrait chercher un autre port disponible mais dans ce cas-ci ce n'est pas le cas. Par contre sous MAMP, ça fonctionne.

**Comment by louis-ev** [comment]
Voir du côté de portscanner https://github.com/baalexander/node-portscanner/issues
Malheureusement il n’y a aucune issue qui correspond…

**Comment by louis-ev** [comment]
Erreur très spécifique (utilisation du même port pour faire tourner un server php) et aucune solution du côté de la bibliothèque utilisée…
Je ferme pour l’instant, si qqun d’autre rencontre cette erreur il faudrait fouiller du côté d’autres libs et voir si elles détectent que le port PHP est pris.
