### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by clemsos** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#66]
Il serait super d'avoir la possibilité de traduire l'interface, par un support i18n par exemple.

**Comment by louis-ev** [comment]
Oui, c'est une bonne idée ! Français Anglais pour commencer.

**Notes pour l’implémentations future**

Le plus simple serait de stocker dans un .json l’ensemble des textes, et de tous les charger une fois au démarrage. Les clients reçoivent l’ensemble des textes et Vue s’occupe de ne charger que la langue demandée (par exemple avec https://kazupon.github.io/vue-i18n/en/ ).

Voir le système de traduction de dodoc https://github.com/l-atelier-des-chercheurs/dodoc/blob/8546ea0abde81f9c9259c1f32fb1be91c668066c/dodoc.js


Avantage : une seule station de doc pourrait permettre de collaborer entre anglophone et francophone à la même documentation.

Inconvénient : les clients reçoivent toutes les langues même celles dont ils n’ont pas besoin. Ou sinon n’envoyer que la langue demandée mais ça demande une requête en plus et un rechargement au changement de langue. À voir en fct de la quantité de texte à traduire.

**Comment by louis-ev** [comment]
Bonjour,

la version 1.1.0 est en ligne avec la traduction en anglais de l’interface. Par défaut, c’est la langue du système qui est sélectionnée mais elle peut être modifiée pour chaque utilisateur.

Pouvez-vous tester de votre côté avant une diffusion plus large ? 

![dec -08-2017 20-27-12](https://user-images.githubusercontent.com/1948417/33781797-3b4161d8-dc56-11e7-90ee-8ec6214535dc.gif)
