### ISSUE TITLE
déplacer les images plus facilement dans la timeline

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#68]
Avec une raccourci clavier ? Shift + click/drag = déplacement dans le temps ?
Autre solution proposée par Mathilde : 
> Sur les éléments j’ajouterais un coin qu’on pourrait attraper pour mettre le visuel ou on veut dans la timeline. Je crois que pour moi savoir l’heure exacte est moins interessante que d’avoir un ordre chronologique bien clair.

**Comment by ThibM** [comment]
Et sur teléphone en restant appuyé sur les médias ? (comme pour faire gigoter les apps qu'on veut éditer)
