### ISSUE TITLE
Augmenter l'échelle possible de la timeline (semaines et mois)

### ISSUE THREAD

**Issue by piapandelakis** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#73]
Hello ! 
J'ai commencé à utiliser ton outil (trop cool !) par contre pour le genre de projets sur lequel je travaille j'aurais besoin d'échelles de temps plus grandes, à la semaine, au mois... 
merci et félicitations pour cet outil hyper prometteur :)

**Comment by louis-ev** [comment]
Bonjour !

merci pour les retours :)

Le problème d’échelles de ce type pareil est de se retrouver avec tellement de médias à afficher en une fois que l’appli rame beaucoup et que ça devienne inutilisable.
Il y a un très gros travail d’optimisation déjà réalisé pour qu’une documentation de 6 mois contenant plusieurs milliers de médias ne ralentisse pas (un script qui observe les éléments qui doivent êtres chargés et ceux qui peuvent être virés du DOM) et une fonctionnalité comme ça risque de faire exploser le compteur.

J’ai fais un test rapide sur un temps avec assez peu de médias, ça donne ça : 

![image](https://user-images.githubusercontent.com/1948417/33957092-e9f08cf2-e040-11e7-91f5-07645ede7eb2.png)

Au-delà de cette échelle peut-être qu’il faudrait repenser l’interface et avoir un affichage un peu différent ?

**Comment by piapandelakis** [comment]
Oui, en effet... dans ma tête on allongeait la timeline parce qu'on postait du contenu de manière plus sporadique... (genre une image/jour). Mais peut-être que même là ça coince ! Sinon, reste l'idée qui consisterait à faire des "paquets" de fichiers mais cela fera peut-être sortir le logiciel de son esprit d'origine. Finalement on peut aussi dire que le logiciel impose un tempo... et que d'autres outils conviennent mieux pour des projets au long cours. En tout cas, j'ai des ami/e/s metteur/se/s en scène, je vais leur en parler.

**Comment by louis-ev** [comment]
Oui !

Pour être plus clair, l’interface n’a aucun soucis à afficher une échelle de ce type, ma réserve porte sur le fait qu’en ayant une bonne quantité de médias répartis sur plusieurs semaines, on risque de faire planter l’application sans le vouloir en passant à cette échelle.

Dans les cas d’usage envisagés lors de la création initiale de l’app, on comptait environ 150 médias (tous types confondus, photos, textes, images, etc.) par jour. L’app est optimisée pour tourner correctement sur un ordinateur d’entrée de gamme, et avec environ 300 médias affichés en même temps on est à la limite haute de ce qu’ont peut afficher. Du coup l’idée de passer dans une autre vue, qui n’affiche que des petits aperçus non empilés de médias semble justifiée.

En tout cas il faudra certainement pouvoir gérer les longs projets dans un temps proche dans cette application, donc n’hésitez pas à continuer d’échanger à ce sujet ! Je poste rapidement un screenshot de calendrier en vue "mois", car ça pourrait être un début de réponse.

![image](https://user-images.githubusercontent.com/1948417/34273729-dfbd5124-e695-11e7-970a-4e3b9e0ac2bb.png)
