### ISSUE TITLE
Mise à jour du readme

### ISSUE THREAD

**Issue by annemarie35** [l-atelier-des-chercheurs/Les-Cahiers-du-Studio#74]
Bonjour,

Je n'ai pas trouvé de wiki, j'espère que ma question ne se trouve pas au mauvais endroit.
Je suis en train de suivre le readme et je voulais vous signaler que la commande `npm run rebuild` n'existe plus. 
Je continue mon installation ^^

**Comment by louis-ev** [comment]
Merci ! C'est effectivement le cas, on va corriger ça.
La commande n’est de toute façon plus utile puisque le script `postinstall` se charge de ça.
Merci encore pour les retours !
